### ISSUE TITLE
I'm so tired for modify your source code

### ISSUE THREAD

**Issue by hqsoft** [saminiir/level-ip#22]
there is no udp , no bind...  I'm burn the midnight oil to add the missing implementation day by day

**Comment by saminiir** [comment]
I'm currently adding NETLINK support (branch `devel` currently) and I admit, adding new socket types could be easier.

There's a fair amount of duplication in the code. This could be lessened with wise use of function pointers, etc. 

Also, a document describing how to add a new socket type would be beneficial, and how the `ipc` module works.
