### ISSUE TITLE
hello there, it's very confused here

### ISSUE THREAD

**Issue by hqsoft** [saminiir/level-ip#23]
int socket_rd_acquire(struct socket *sock)
{
    int rc = pthread_rwlock_wrlock(&sock->lock);
    sock->refcnt++;
    return rc;
}

int socket_wr_acquire(struct socket *sock)
{
    int rc = pthread_rwlock_wrlock(&sock->lock);
    sock->refcnt++;
    return rc;
}

int socket_release(struct socket *sock)
{
    int rc = 0;
    sock->refcnt--;

    if (sock->refcnt == 0) {
        rc = pthread_rwlock_unlock(&sock->lock);
        free(sock);
    } else {
        rc = pthread_rwlock_unlock(&sock->lock);
    }

    return rc;
}

**Comment by saminiir** [comment]
So the idea is to preserve the socket thread memory safety by implementing reference counting to the data structure. This is one of the simplest approaches possible, and suffers from error-prone semantics (lock & unlock) and the performance is sub-par.

Whenever a caller (application, incoming messages from network..)  want a socket to do work, the caller needs to acquire a lock to it. Those functions are utility functions for this - the socket's mutex is (un)locked and the reference count is increased/decreased.

There seems to be a bug in that socket_rd_acquire should really do `pthread_rwlock_rdlock`.
