### ISSUE TITLE
there may be some problem with tcp checksum!

### ISSUE THREAD

**Issue by lishuhuakai** [saminiir/level-ip#8]
I spend several weeks read and debug the code, and I had learned a lot, thanks.

And I spend a lot of time in debuging tcp tree-way handshark, I tested a lot, and today I finally got the result I want, and I find the problem:

 in tcp.c -->tcp_udp_checksum --> line 95 sum += htons(proto); 
should it be sum += proto ?

when checksum is wrong,and the system will discard the package, I send a lot of syn to tap0, and tap0 didn't response to me, and I use wireshark capture the package, and find the checksum was wrong, and today I fixed the checksum bug, and tap0 send ack and syn to me.

my english is poor.hope you can understand the meaning I want to express.

**Comment by saminiir** [comment]
Hey! I'm glad you've found the code useful.

I think I understand your issue. The checksum calculation can easily break, e.g. at least big-endian Linux systems are not supported at the moment. Can you fill in some more details about your environment?

```
$ cat /etc/os-release
$ uname -a
```

I am running the following setup:
```
[saminiir@localhost level-ip]$ cat /etc/os-release
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
VERSION_ID="2015.11.01"
[saminiir@localhost level-ip]$ uname -a
Linux localhost 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```

Hence, it's a little-endian Linux system. I tried changing the byte-ordering in `tcp_udp_checksum`, but that makes the checksum go wrong for me.

Let's continue troubleshooting, but I need more details about your system for starters.

**Comment by lishuhuakai** [comment]
My fixed code are as follows:
[https://github.com/lishuhuakai/ToyIP/blob/master/checksum.h](https://github.com/lishuhuakai/ToyIP/blob/master/checksum.h)
[https://github.com/lishuhuakai/ToyIP/blob/master/checksum.c](https://github.com/lishuhuakai/ToyIP/blob/master/checksum.c)
`
% cat /etc/os-release
PRETTY_NAME="Deepin 15"
NAME="Deepin"
VERSION_ID="15.4"
VERSION="15.4"
ID=deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="http://feedback.deepin.org/feedback/"
% uname -a
Linux Yihulee-PC 4.9.0-deepin4-amd64 #1 SMP PREEMPT Deepin 4.9.8-4 (2017-04-17) x86_64 GNU/Linux
`
and my system blongs to little-endian system.

**Comment by lishuhuakai** [comment]
Noting wrong with your code, I just test the origin code, and it works fine. Probably I changed some code that lead the checksum go wrong When I reading the code,Sorry to bother you.

**Comment by saminiir** [comment]
No problem.

Closing the issue, because it seems to be resolved.
